### ISSUE TITLE
Table keybindings do not work

### ISSUE THREAD

**Issue by Cutuchiqueno** [tgrosinger/table-editor-obsidian#10]
I am on Manjaro Linux with Obsidian 0.9.10

For me the default keybindings (<tab> for next cell; <return> for next row etc.) do not work, that is to say they do what I expect them to do outside of a table (indent; insert line break etc.)

Using the command palette, the functions themselves work well.

**Comment by tristanbailey** [comment]
I have the same on My Mac 10.14.6 with obsidian 0.9.10, 
The demo image suggests these changes should track the keyboard live and tab work but they do not for me. Choosing form the Menu apple-p seems to work.

**Comment by malife** [comment]
Yes, it does not seem to work on macOS. I can toggle the toolbar by CMD+D and commands do seem to work, however navigating between columns CTRL+TAB, SHIFT+TAB, ALT+TAB do not work. For non-macOS users CMD+TAB is out of the question as that is the universal binding for application switching (equivalent to ALT+TAB in Windows).

**Comment by tgrosinger** [comment]
Hello,
Can I check with everyone that you have installed version 0.4.0 of the table-editor plugin? Also please make sure you are using <kbd>tab</kbd>, <kbd>shift</kbd>+<kbd>tab</kbd>, and <kbd>enter</kbd>. The previous keybindings which used <kbd>ctrl</kbd> were only temporary and are no longer used by this plugin.

**Comment by mafsi** [comment]
Ctrl+Shift+d is not working. Everything else, does! 0.9.10

**Comment by mafsi** [comment]
Which one should be? to see all the commands like in your presentation? Btw: I'm on Windows
https://ibb.co/8Pxdr4F

**Comment by tgrosinger** [comment]
Oh great question. Sorry I didn't make that more clear. Here's the one you're looking for:

![Toolbar-hotkey](https://user-images.githubusercontent.com/597386/97902859-07e4d500-1cf3-11eb-9f22-eb739e80dc32.png)

**Comment by mafsi** [comment]
that is weird.. That command appears only when I change Obsidian language in English. In my  language is not appearing...

**Comment by tgrosinger** [comment]
Haha yeah, I wanted to give people flexibility in how it gets configured. I am glad to hear that re-binding it solved the problem. I am confused why ctrl+shift+d did not work on Windows though. That's where I am using it. Maybe something else is also bound to that hotkey for you?

**Comment by mafsi** [comment]
> 
> 
> Haha yeah, I wanted to give people flexibility in how it gets configured. I am glad to hear that re-binding it solved the problem. I am confused why ctrl+shift+d did not work on Windows though. That's where I am using it. Maybe something else is also bound to that hotkey for you?

No, wasn't binding...I don't know why in the fist place didn't work. Man, we are out of key on keyboard :))

**Comment by malife** [comment]
I can confirm that after configuring the hotkeys everything works as expected. I would recommend mentioning this in the README to avoid further questions. 

This plugin is awesome!

**Comment by tgrosinger** [comment]
@Cutuchiqueno looks like your original question is the only one unresolved in this ticket. Let me know if any of the conversation above helps, or if you are still having the issue.

Thanks.

**Comment by Cutuchiqueno** [comment]
I was able to solve the problem by uninstalling and reinstalling the plugin. Before and after the reinstall the version I used was 0.4 so the reason will remain a mystery :D what counts is the result. Thx.

**Comment by tgrosinger** [comment]
Great, thanks for the update. Glad to hear it's working.
