### ISSUE TITLE
Include image

### ISSUE THREAD

**Issue by dxcore35** [tgrosinger/table-editor-obsidian#2]
Please include image or animated gif what the plugins is doing.

**Comment by tgrosinger** [comment]
I think this would be excellent to add, however it is not something I have experience in creating. I'd love help with this if someone is so inclined.

In the mean time, the functionality is very similar to that demonstrated in the gif here: https://github.com/susisu/mte-kernel

**Comment by dxcore35** [comment]
You can use CloudApp, it is really good app when sharing anything online: making gif from screen, video recording, screenshots... have it a go https://www.getcloudapp.com

**Comment by tgrosinger** [comment]
I ended up using [ScreenToGif](https://www.screentogif.com/) because it allowed me to display keystrokes and gave me a lot more control in editing the result.

Thanks for the suggestion.
