### ISSUE TITLE
Is it possible to add an ID or class to a table so they can be individually styled with CSS?

### ISSUE THREAD

**Issue by ThornedRose** [tgrosinger/table-editor-obsidian#255]
**Is your feature request related to a problem? Please describe.**
I have multiple tables in a note, however the first table contains something akin to metadata and needs to be styled differently from all the other tables.

**Describe the solution you'd like**
I would love some way of adding CSS classes to individual tables so that they can be styled differently depending on need.

**Describe alternatives you've considered**
I have tried using the current recommended markdown suggestions such as putting a {.class} after the markdown block (in this case a table), wrapping the table in a `<div class="">`, putting a unique div before the table and targeting after, CSS alone such as nth-child, etc. but nothing works :(

**Comment by tgrosinger** [comment]
This plugin only affects editing the data and structure of a table. It does not affect table styling. Please work with the Obsidian developers on this issue.
