### ISSUE TITLE
Add setting for toggling between normal and weak formatting

### ISSUE THREAD

**Issue by tgrosinger** [tgrosinger/table-editor-obsidian#4]
Weak formatting would be better for people not using a monospaced font in the un-rendered view.

**Comment by DutchPete** [comment]
What do you mean by weak formatting?

**Comment by tgrosinger** [comment]
Referring to the fomatting types [described here](https://doc.esdoc.org/github.com/susisu/mte-kernel/variable/index.html#static-variable-FormatType).


    FormatType.NORMAL - Formats table normally.
    FormatType.WEAK   - Formats table weakly, rows are formatted independently to each other, cell contents are just trimmed and not aligned.

In other words, when using weak formatting, it will not insert a bunch of spaces to pad out the cells to the same width in all rows. When not using a monospaced font it does not make sense to perform this padding since spaces are very narrow in non-monospace fonts and they don't work right for padding.

**Comment by tgrosinger** [comment]
Fixed in https://github.com/tgrosinger/table-editor-obsidian/commit/1b765db7b4d520865ecf4066521e3f7ac94e116d
