### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by ngirard** [tgrosinger/table-editor-obsidian#8]
Using: Table editor 0.3.2 / Obsidian 0.9.10 / Ubuntu 20.04.

After loading Table editor, the following error pops up in the console:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
https://github.com/tgrosinger/table-editor-obsidian/releases/download/0.3.2/styles.css
```

**Comment by tgrosinger** [comment]
Currently this plugin does not use or provide a styles.css, so that error is expected. Thank you for checking though 🙂
